---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/mapas_RevCasparya/mapas_RevCasparya.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/284375/articles/407070/master/file/figures/mapas_RevCasparya/mapas_RevCasparya.png"
