---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/cornuta/cornuta.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/284375/articles/407070/master/file/figures/cornuta/cornuta.png"
    folder_url: "/users/284375/articles/407070/master/folder/figures/cornuta"
